Repository jcruiz22/practica-valuable-pipeline, pull requests merged in 2024-02, with the labels that each got.

#26 feat:
  test/helloWorld.test.js
Labels: patch

#27 vamoooos
  .github/workflows/semver.yml
Labels: patch

#28 removes semantic-release yml
  .github/workflows/release.yml
Labels: major

#29 feat
  src/app.js
  test/helloWorld.test.js
Labels: major

#30 feat
  src/app.js
  test/helloWorld.test.js
Labels: minor

#31 message changed
  src/app.js
  test/helloWorld.test.js
Labels: major

#32 AA
  .github/workflows/CICD.yml
  .github/workflows/tests.yml
Labels: minor

#35 fix: msj diferente
  src/app.js
  test/helloWorld.test.js
Labels: major

#36 fix: nuevo mensaje
  src/app.js
  test/helloWorld.test.js
Labels: major
